### ISSUE TITLE
error cpnfig file

### ISSUE THREAD

**Issue by necatiCelik** [preronamajumder/deepstream-lpr-python-version#1]

**Comment by necatiCelik** [comment]
Hi,
Thanks your codes. But I have a error this code. Error is;


Creating Pipeline 
 
Creating streamux 
 
Creating source_bin  0  
 
file://file:////home/lpr/Downloads/sample_output.mp4
*********************
Creating source bin
source-bin-00
Creating Pgie 
 
Creating tiler 
 
Creating nvdsanalytics 
 
Creating nvvidconv1 
 
Creating filter1 
 
Creating tiler 
 
Creating nvvidconv 
 
Creating nvosd 
 
Creating transform 
 
Creating EGLSink 

Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
Unknown or legacy key specified 'process_mode' for group [property]
Adding elements to Pipeline 

Linking elements in the Pipeline 

Now playing...
4 :  file:////home/lpr/Downloads/sample_output.mp4
Starting pipeline 


Using winsys: x11 
ERROR: Deserialize engine failed because file path: /opt/nvidia/deepstream/deepstream-5.0/sources/apps/deepstream-lpr-python-version/./models/LP/LPR/lpr_us_onnx_b32.engine open error
0:00:01.402321806 10927     0x164f1aa0 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1690> [UID = 2]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-5.0/sources/apps/deepstream-lpr-python-version/./models/LP/LPR/lpr_us_onnx_b32.engine failed
0:00:01.402542746 10927     0x164f1aa0 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1797> [UID = 2]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-5.0/sources/apps/deepstream-lpr-python-version/./models/LP/LPR/lpr_us_onnx_b32.engine failed, try rebuild
0:00:01.402676097 10927     0x164f1aa0 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1715> [UID = 2]: Trying to create engine from model files
ERROR: failed to build network since there is no model file matched.
ERROR: failed to build network.
0:00:01.403033331 10927     0x164f1aa0 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1735> [UID = 2]: build engine file failed
0:00:01.403070933 10927     0x164f1aa0 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1821> [UID = 2]: build backend context failed
0:00:01.403103543 10927     0x164f1aa0 ERROR                nvinfer gstnvinfer.cpp:613:gst_nvinfer_logger:<secondary2-nvinference-engine> NvDsInferContext[UID 2]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1148> [UID = 2]: generate backend failed, check config file settings
0:00:01.403879872 10927     0x164f1aa0 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<secondary2-nvinference-engine> error: Failed to create NvDsInferContext instance
0:00:01.403929186 10927     0x164f1aa0 WARN                 nvinfer gstnvinfer.cpp:809:gst_nvinfer_start:<secondary2-nvinference-engine> error: Config file path: lpr_config_sgie_us.txt, NvDsInfer Errororororororororo

**Comment by preronamajumder** [comment]
Hi,

your source is file:////home/lpr/Downloads/sample_output.mp4. It should be file:///home/lpr/Downloads/sample_output.mp4
your source has 4 forward slashes. It should be 3 forward slashes.

file://<copy paste your full video path here>

This will automatically add a 3rd forward slash.

**Comment by preronamajumder** [comment]
Hi,

your model file path is wrong or its name is wrong. It seems it cannot find the model with the name provided in the config.

Take note that deepstream uses relative paths. Do not put full pathname in the config.

Did you download the models as mentioned in the Readme?

Also your source is file:////home/lpr/Downloads/sample_output.mp4. It should be file:///home/lpr/Downloads/sample_output.mp4
your source has 4 forward slashes. It should be 3 forward slashes.

something like this: file:///home/Downloads/output.mp4

**Comment by necatiCelik** [comment]
Thanks, 
I managed to fix it and run it. However, I am trying to read "Turkish license plates". How I need to follow a path.
Thank you very much for your help

**Comment by preronamajumder** [comment]
For Turkish you need to train a classifier based on Turkish license plate. The OCR training procedure is a bit different in Deepstream. You should go through their official website to know more on how they trained their model and if any questions then you can post in their forums.
