### ISSUE TITLE
Unable to create lpr engine file

### ISSUE THREAD

**Issue by vinodbukya6** [preronamajumder/deepstream-lpr-python-version#4]
Hi, I am working on License plate recognition problem. I have followed same steps as mentioned in the repo with Deepstream 6.0, When I run deepstream app i am facing following issue.

Starting pipeline

0:00:00.209260524 226 0x1a87b20 INFO nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger: NvDsInferContext[UID 3]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 3]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: ShapedWeights.cpp:173: Weights td_dense/kernel:0 has been transposed with permutation of (1, 0)! If you plan on overwriting the weights with the Refitter API, the new weights must be pre-transposed.
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [TRT]: Detected invalid timing cache, setup a local cache instead
python3: /dvs/p4/build/sw/rel/gpgpu/MachineLearning/myelin_trt8/src/compiler/optimizer/cublas_impl.cpp:477: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vectormyelin::ir::tactic_attribute_t&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.
Aborted (core dumped)

Can anyone please help me on how to solve this issue?

**Comment by imSrbh** [comment]
@preronamajumder

**Comment by vinodbukya6** [comment]
Hi, LPR engine file created using tlt-converter and followed mentioned steps.
Deepstream 5.1, cuda 11.1, TensorRT 7.2.
It's working fine for command: 
python3 deepstream_lpr_app.py 1 2 0 file:///opt/nvidia/deepstream/deepstream-5.1/samples/streams/lpr-test1.mp4 out.mp4

Thank you so much for Python version lpr.

**Comment by imSrbh** [comment]
@vinodbukya6 
What about with Deepstream 6.0??

not for Deepstream 5.1, cuda 11.1, TensorRT 7.2.

is this repo working in DS 6.0?
